spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: "mongodb+srv://it24100688_db_user:urAbAz3iMIz6ydmZ@account-db.u2fxpoc.mongodb.net/account-db?retryWrites=true&w=majority&appName=account-db"

server:
  port: 8081
